version: '3'
services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /devoluciones-ui
    command: sh -c "npm run build && npm start"